[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
